site_name: "sbijax"
site_description: Documentation for sbijax
site_url: https://sbijax.readthedocs.io
repo_url: https://github.com/dirmeier/sbijax
repo_name: dirmeier/sbijax
edit_uri: ""

nav:
  - 🏠 Home: 'index.md'
  - 📰 News: 'news.md'
  - 🎓 Tutorials:
      - notebooks/introduction.ipynb
      - notebooks/high_dimensional_inference.ipynb
  - 🎓 Example code:
      - 'examples.md'
  - References: 'references.md'
  - 🧱 API:
      - <code>sbijax</code>: sbijax.md
      - <code>sbijax.mcmc</code>: sbijax.mcmc.md
      - <code>sbijax.nn</code>: sbijax.nn.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes

plugins:
  - search
  - mkdocs-jupyter
  - autorefs
  - bibtex:
      bib_file: "docs/references.bib"
      csl_file: "https://raw.githubusercontent.com/citation-style-language/styles/af38aba0e9b08406c8827abfc888e5f3e3fa1d65/journal-of-the-royal-statistical-society.csl"
      cite_inline: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 3
            show_root_heading: true
            show_root_full_path: true
            show_root_toc_entry: true
            show_symbol_type_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
            show_source: false
            inherited_members: true
            docstring_style: "google"


extra_css:
  - _static/theme.css