name: examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  precommit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  examples:
    runs-on: ubuntu-latest
    needs:
      - precommit
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install hatch matplotlib
      - name: Build package
        run: |
          pip install jaxlib jax
          pip install .
      - name: Run tests
        run: |
            python examples/bivariate_gaussian-smcabc.py --n-rounds 1
            python examples/mixture_model-cmpe.py --n-iter 10
            python examples/mixture_model-nle.py --n-iter 10
            python examples/mixture_model-nle.py --n-iter 10 --use-spf
            python examples/mixture_model-npe.py --n-iter 10
            python examples/mixture_model-nre.py --n-iter 10
            python examples/slcp-fmpe.py --n-iter 10
            python examples/slcp-nass_nle.py --n-iter 10 --n-rounds 1
            python examples/slcp-nass_smcabc.py --n-iter 10 --n-rounds 1
            python examples/slcp-snle.py --n-iter 10  --n-rounds 1
